### ISSUE TITLE
FileNotFoundError if FFXIV is not installed to default location

### ISSUE THREAD

**Issue by Akurosia** [icykoneko/saintcoinach-py#1]
In file "ff14-fish-tracker-app\private\saintcoinach-py\pysaintcoinach\__init__.py" line 66/67 produce a FileNotFoundError when ffxiv is not installed in default location.

Also when accessed from your "ff14-fish-tracker-app", it also throws an error due to this line (even if i use the -gpath parameter)

Is this line neccassary or can it be removed?

**Comment by icykoneko** [comment]
Yea, it can be removed. Doesn't appear super necessary.
