### ISSUE TITLE
In Sheet.get_raw(column_name) can‘t’ get the result

### ISSUE THREAD

**Issue by CodeZWT** [icykoneko/saintcoinach-py#4]
Hi，In the Code

> FISHING_NODES = dict([
>     (spot.key,
>         dict([('_id', spot.key),
>             *_make_localized_field('name', spot['PlaceName'], 'Name'),
>             ('territory_id', spot.get_raw('TerritoryType')),
>             ('placename_id', spot.key)]))
>     for spot in XIV.game_data.get_sheet('FishingSpot')
>     if spot.get_raw('PlaceName{Main}') == 0])

in the  

> if spot.get_raw('PlaceName{Main}') == 0])

i can‘t get the result with ther error

> ’  File "C:\Users\CodeZ\Desktop\EorzeaJS\pysaintcoinach\ex\relational\header.py", line 41, in get_column
>     return self.__columns[index]
> IndexError: list index out of range

the index is “22”，but the sheet “FishingSpot” rows length is “21”，

the sheet_definition is 

>  SheetDefinition(DataDefinitions=
> [PositionedDataDefinition(Index=0, InnerDefinition=SingleDataDefinition(Name='GatheringLevel', Converter=None)), 
> PositionedDataDefinition(Index=1, InnerDefinition=SingleDataDefinition(Name='BigFish{OnReach}', Converter=None)),
> PositionedDataDefinition(Index=2, InnerDefinition=SingleDataDefinition(Name='BigFish{OnEnd}', Converter=None)), 
> PositionedDataDefinition(Index=3, InnerDefinition=SingleDataDefinition(Name='FishingSpotCategory', Converter=None)),
> PositionedDataDefinition(Index=4, InnerDefinition=SingleDataDefinition(Name='Rare', Converter=None)), 
>  PositionedDataDefinition(Index=5, InnerDefinition=SingleDataDefinition(Name='TerritoryType', Converter=SheetLinkConverter(TargetSheet='TerritoryType'))), 
>PositionedDataDefinition(Index=6, InnerDefinition=SingleDataDefinition(Name='PlaceName{Main}', Converter=SheetLinkConverter(TargetSheet='PlaceName'))),
> PositionedDataDefinition(Index=7, InnerDefinition=SingleDataDefinition(Name='PlaceName{Sub}', Converter=SheetLinkConverter(TargetSheet='PlaceName'))),
> PositionedDataDefinition(Index=8, InnerDefinition=SingleDataDefinition(Name='X', Converter=None)),
> PositionedDataDefinition(Index=9, InnerDefinition=SingleDataDefinition(Name='Z', Converter=None)),
> PositionedDataDefinition(Index=10, InnerDefinition=SingleDataDefinition(Name='Radius', Converter=None)), 
> PositionedDataDefinition(Index=12, InnerDefinition=RepeatDataDefinition(NamingOffset=0, RepeatCount=10, RepeatedDefinition=SingleDataDefinition(Name='Item', Converter=SheetLinkConverter(TargetSheet='Item')))), 
> PositionedDataDefinition(Index=22, InnerDefinition=SingleDataDefinition(Name='PlaceName', Converter=SheetLinkConverter(TargetSheet='PlaceName'))), 
> PositionedDataDefinition(Index=23, InnerDefinition=SingleDataDefinition(Name='Order', Converter=None))], Name='FishingSpot', DefaultColumn='PlaceName', IsGenericReferenceTarget=False)

the sheet column_name is

> key,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
> key,GatheringLevel,BigFish{OnReach},BigFish{OnEnd},FishingSpotCategory,Rare,TerritoryType,X,Z,Radius,,Item[0],Item[1],Item[2],Item[3],Item[4],Item[5],Item[6],Item[7],Item[8],Item[9],PlaceName,Order
> 

My FFXIV Patch is 5.18 in Cn server and the game language is chinese_simplified

Can you help me,please
thanks,and have a good time

**Comment by icykoneko** [comment]
Looks like 5.2 changed that table which is causing the errors. Since I don’t track the CN version myself I can’t account for this sorry. If you want to use this library still with an older patch, try switching to a previous commit.

I usually only update my version when a new patch is released so it shouldn’t be too hard.
