### ISSUE TITLE
Pillow library is out of date

### ISSUE THREAD

**Issue by icykoneko** [icykoneko/saintcoinach-py#6]
Need to upgrade Pillow, but the latest version didn't build for me on Python 3.9.  Need to look into this further...

**Comment by micahlaster** [comment]
fixed this on python 3.9.2 by changing Pillow ~= 6.2 in requirements.txt to Pillow ~= 8.0.0 and it grabbed version 8.0.1 which works

**Comment by icykoneko** [comment]
Sorry this took so long to update... Updated the requirements to ~=9.5 for now.
